# Generated by Django 4.1.7 on 2023-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('pinyin', models.CharField(default='wuzhi', max_length=30, verbose_name='拼音')),
                ('sex', models.CharField(max_length=5, verbose_name='性别')),
                ('bir', models.CharField(max_length=50, verbose_name='出生日期')),
                ('ass', models.CharField(max_length=30, verbose_name='地址')),
                ('sto', models.TextField(verbose_name='故事')),
            ],
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_object', models.CharField(max_length=30, verbose_name='名称')),
                ('like_num', models.IntegerField(verbose_name='点赞数')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_mail', models.CharField(max_length=100)),
                ('reg_pwd', models.CharField(max_length=100)),
                ('reg_name', models.CharField(default='优秀学子', max_length=22)),
                ('reg_sex', models.CharField(default='未知', max_length=6)),
                ('reg_lookscore', models.IntegerField(default=0, verbose_name='浏览积分')),
                ('reg_lovescore', models.IntegerField(default=0, verbose_name='点赞积分')),
                ('reg_testscore', models.IntegerField(default=0, verbose_name='答题积分')),
            ],
        ),
    ]
